<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>auv_lane_follow</name>
  <version>0.1.0</version>
  <description>Yonlendirme tahtasi serit takibi (D435 renk -> hiz komutu)</description>
  <maintainer email="thelicbd@yeniaycerez.com">AUV Takimi</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>auv_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
